/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomeAffairsPackage;

/**
 *
 * @author byronkraus
 */
public class ActionPerformedScreen extends javax.swing.JFrame {

    /**
     * Creates new form ImageDisplay
     *
     * @param input
     */
    public ActionPerformedScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        BlackBorder = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();
        TickImage = new javax.swing.JLabel();
        SuccessLabel = new javax.swing.JLabel();
        ContinueButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setOpaque(false);
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BlackBorder.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home Affairs Online");

        javax.swing.GroupLayout BlackBorderLayout = new javax.swing.GroupLayout(BlackBorder);
        BlackBorder.setLayout(BlackBorderLayout);
        BlackBorderLayout.setHorizontalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlackBorderLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1))
        );
        BlackBorderLayout.setVerticalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BlackBorderLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1))
        );

        Background.add(BlackBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 566, -1));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/view/images/Picture 2.png"))); // NOI18N
        Background.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 560, 260));

        TickImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/view/images/green-tick-clipart-green-tick-234 copy.jpg"))); // NOI18N
        Background.add(TickImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 60, 240, 230));

        SuccessLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        SuccessLabel.setText("Success!");
        Background.add(SuccessLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 90, 20));

        ContinueButton.setBackground(new java.awt.Color(255, 255, 255));
        ContinueButton.setText("CONTINUE");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });
        Background.add(ContinueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 100, 40));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 566, 338));

        setSize(new java.awt.Dimension(566, 348));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

// Screen changes once continue button is clicked.
    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        this.dispose();
        WelcomeScreen eng = new WelcomeScreen();
        eng.setVisible(true);
    }//GEN-LAST:event_ContinueButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActionPerformedScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActionPerformedScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActionPerformedScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActionPerformedScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActionPerformedScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel BlackBorder;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JLabel SuccessLabel;
    private javax.swing.JLabel TickImage;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
