/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomeAffairsPackage;

import java.awt.Color;

/**
 *
 * @author byronkraus
 */
public class AddStaffMember extends javax.swing.JFrame {

    /**
     * Creates new form ImageDisplay
     */
    public AddStaffMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        BlackBorder = new javax.swing.JPanel();
        HomeAffairsLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        NameLabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        SurnameLabel = new javax.swing.JLabel();
        SurnameField = new javax.swing.JTextField();
        AddStaffMemberLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        ContinueButton = new javax.swing.JButton();
        BackgroundImage = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        RoleLabel = new javax.swing.JLabel();
        RoleField = new javax.swing.JTextField();
        StaffLabel = new javax.swing.JLabel();
        AdminLabel = new javax.swing.JLabel();
        MiddleNameLabel = new javax.swing.JLabel();
        MiddleNameField = new javax.swing.JTextField();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        LogOutMenu = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setOpaque(false);
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BlackBorder.setBackground(new java.awt.Color(0, 0, 0));

        HomeAffairsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        HomeAffairsLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeAffairsLabel.setText("Home Affairs Online");

        javax.swing.GroupLayout BlackBorderLayout = new javax.swing.GroupLayout(BlackBorder);
        BlackBorder.setLayout(BlackBorderLayout);
        BlackBorderLayout.setHorizontalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(HomeAffairsLabel)
                .addGap(166, 166, 166))
        );
        BlackBorderLayout.setVerticalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(HomeAffairsLabel)
                .addContainerGap())
        );

        background.add(BlackBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        IDLabel.setText("Enter your ID");
        background.add(IDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, -1, -1));

        IDField.setForeground(new java.awt.Color(204, 204, 204));
        IDField.setText("6801023487265");
        IDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDFieldFocusLost(evt);
            }
        });
        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });
        background.add(IDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 200, -1));

        NameLabel.setText("Enter your full name");
        background.add(NameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 130, -1, -1));

        NameField.setForeground(new java.awt.Color(204, 204, 204));
        NameField.setText("John");
        NameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                NameFieldFocusLost(evt);
            }
        });
        background.add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 130, 200, -1));

        SurnameLabel.setText("Enter your Surname");
        background.add(SurnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 195, -1, -1));

        SurnameField.setForeground(new java.awt.Color(204, 204, 204));
        SurnameField.setText("Williamson");
        SurnameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SurnameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SurnameFieldFocusLost(evt);
            }
        });
        background.add(SurnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 195, 200, -1));

        AddStaffMemberLabel.setText("Add a new Staff member");
        background.add(AddStaffMemberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        PasswordLabel.setText("Enter a password");
        background.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 230, -1, -1));

        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        background.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 70, 40));

        ContinueButton.setText("CONTINUE");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });
        background.add(ContinueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, -1, 40));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/view/images/Picture 2.png"))); // NOI18N
        BackgroundImage.setToolTipText("");
        background.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 560, 270));

        PasswordField.setForeground(new java.awt.Color(204, 204, 204));
        PasswordField.setText("Fred1335");
        PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusLost(evt);
            }
        });
        background.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 200, 30));

        RoleLabel.setText("Enter your role");
        background.add(RoleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 95, -1, -1));

        RoleField.setForeground(new java.awt.Color(204, 204, 204));
        RoleField.setText("0");
        RoleField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RoleFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RoleFieldFocusLost(evt);
            }
        });
        RoleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoleFieldActionPerformed(evt);
            }
        });
        background.add(RoleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 95, 200, -1));

        StaffLabel.setText("(1 - Staff member)");
        background.add(StaffLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, -1));

        AdminLabel.setText("(2 - Administrator)");
        background.add(AdminLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        MiddleNameLabel.setText("Enter your middle name");
        background.add(MiddleNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 160, -1, -1));

        MiddleNameField.setForeground(new java.awt.Color(204, 204, 204));
        MiddleNameField.setText("Fred");
        MiddleNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MiddleNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MiddleNameFieldFocusLost(evt);
            }
        });
        background.add(MiddleNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 200, -1));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, -1, -1));

        FileMenu.setText("File");

        LogOutMenu.setText("Log Out");
        LogOutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutMenuActionPerformed(evt);
            }
        });
        FileMenu.add(LogOutMenu);

        HelpMenu.setText("Help");
        HelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpMenuActionPerformed(evt);
            }
        });
        FileMenu.add(HelpMenu);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        setSize(new java.awt.Dimension(569, 375));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
        //no action
    }//GEN-LAST:event_IDFieldActionPerformed

    // Screen changes once back button is clicked.
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        AdministratorHomeScreen eng = new AdministratorHomeScreen();
        eng.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed
    //changes screen if correct info entered
    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        String password = String.valueOf(PasswordField.getPassword());
        StaffManager sm = new StaffManager();
        //checks correct input is made into each field
        if (!(RoleField.getText().equalsIgnoreCase("0"))
                && !(IDField.getText().equalsIgnoreCase("6801023487265"))
                && !(RoleField.getText().equalsIgnoreCase("0"))
                && !(NameField.getText().equalsIgnoreCase("John"))
                && !(SurnameField.getText().equalsIgnoreCase("Fred"))
                && !(SurnameField.getText().equalsIgnoreCase("Williamson"))
                && !(password.equalsIgnoreCase("Fred1335"))) {

            sm.addStaff(IDField.getText(), RoleField.getText(),
                    NameField.getText(), MiddleNameField.getText(),
                    SurnameField.getText(), password);//adds to staff members

            this.dispose();
            ActionPerformedScreen eng = new ActionPerformedScreen();
            eng.setVisible(true);
            // Screen changes once continue button is clicked
        } else {
            System.out.println("Incorrect values entered");
        }
    }//GEN-LAST:event_ContinueButtonActionPerformed

    // Removes example data when user clicks on IDField
    private void IDFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusGained
        if (IDField.getText().equalsIgnoreCase("6801023487265")) {
            IDField.setForeground(Color.black);
            IDField.setText("");
        }
    }//GEN-LAST:event_IDFieldFocusGained

    // Removes example data when user clicks on NameField
    private void NameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFieldFocusGained
        if (NameField.getText().equalsIgnoreCase("John")) {
            NameField.setForeground(Color.black);
            NameField.setText("");
        }
    }//GEN-LAST:event_NameFieldFocusGained

    // Removes example data when user clicks on SurnameField
    private void SurnameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SurnameFieldFocusGained
        if (SurnameField.getText().equalsIgnoreCase("Williamson")) {
            SurnameField.setForeground(Color.black);
            SurnameField.setText("");
        }
    }//GEN-LAST:event_SurnameFieldFocusGained

    // Screen changes once log out button is clicked
    private void LogOutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutMenuActionPerformed
        this.dispose();
        WelcomeScreen eng = new WelcomeScreen();
        eng.setVisible(true);
    }//GEN-LAST:event_LogOutMenuActionPerformed

    // Sets data back to example data when incorrect data is entered
    private void IDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusLost
        if (IDField.getText().equalsIgnoreCase("")
                || !(IDField.getText().length() == 13)
                || IDField.getText().matches("\\d+")) {

            IDField.setForeground(new Color(204, 204, 204));
            IDField.setText("6801023487265");
        }
    }//GEN-LAST:event_IDFieldFocusLost

    // Sets data back to example data when incorrect data is entered
    private void NameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NameFieldFocusLost
        if (NameField.getText().equalsIgnoreCase("")) {
            NameField.setForeground(new Color(204, 204, 204));
            NameField.setText("John");
        }
    }//GEN-LAST:event_NameFieldFocusLost

    // Sets data back to example data when incorrect data is entered
    private void SurnameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SurnameFieldFocusLost
        if (SurnameField.getText().equalsIgnoreCase("")) {
            SurnameField.setForeground(new Color(204, 204, 204));
            SurnameField.setText("Williamson");
        }
    }//GEN-LAST:event_SurnameFieldFocusLost

    // Removes example data when user clicks on PasswordField
    private void PasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusGained
        String password = String.valueOf(PasswordField.getPassword());

        if (password.equalsIgnoreCase("Fred1335")) {
            SurnameField.setForeground(Color.black);
            SurnameField.setText("");
        }
    }//GEN-LAST:event_PasswordFieldFocusGained

    // Sets data back to example data when incorrect data is entered
    private void PasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusLost
        String password = String.valueOf(PasswordField.getPassword());

        if (password.equalsIgnoreCase("")) {
            PasswordField.setForeground(new Color(204, 204, 204));
            PasswordField.setText("Fred1335");
        }
    }//GEN-LAST:event_PasswordFieldFocusLost

    // Removes example data when user clicks on RoleField
    private void RoleFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RoleFieldFocusGained
        if (RoleField.getText().equalsIgnoreCase("0")) {
            RoleField.setForeground(Color.black);
            RoleField.setText("");
        }
    }//GEN-LAST:event_RoleFieldFocusGained

    // Sets data back to example data when incorrect data is entered
    private void RoleFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RoleFieldFocusLost
        if (RoleField.getText().equalsIgnoreCase("")
                || Integer.parseInt(RoleField.getText()) > 2
                || Integer.parseInt(RoleField.getText()) < 0) {

            RoleField.setForeground(new Color(204, 204, 204));
            RoleField.setText("0");
        }
    }//GEN-LAST:event_RoleFieldFocusLost

    private void RoleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoleFieldActionPerformed
        // no action
    }//GEN-LAST:event_RoleFieldActionPerformed

    // Removes example data when user clicks on MiddleNameField
    private void MiddleNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MiddleNameFieldFocusGained
        if (MiddleNameField.getText().equalsIgnoreCase("")) {
            MiddleNameField.setForeground(new Color(204, 204, 204));
            MiddleNameField.setText("Fred");
        }
    }//GEN-LAST:event_MiddleNameFieldFocusGained

    // Sets data back to example data when incorrect data is entered
    private void MiddleNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MiddleNameFieldFocusLost
        if (MiddleNameField.getText().equalsIgnoreCase("")) {
            MiddleNameField.setForeground(new Color(204, 204, 204));
            MiddleNameField.setText("Fred");
        }
    }//GEN-LAST:event_MiddleNameFieldFocusLost
    //accesses internet site for help
    private void HelpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpMenuActionPerformed
        try {
            String url = "https://skaterbyron.wixsite.com/homeaffairsonlinehel";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_HelpMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting 
        //code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the 
        default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing
        /lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : 
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStaffMember.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStaffMember.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStaffMember.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStaffMember.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStaffMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddStaffMemberLabel;
    private javax.swing.JLabel AdminLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel BlackBorder;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem HelpMenu;
    private javax.swing.JLabel HomeAffairsLabel;
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JMenuItem LogOutMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTextField MiddleNameField;
    private javax.swing.JLabel MiddleNameLabel;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField RoleField;
    private javax.swing.JLabel RoleLabel;
    private javax.swing.JLabel StaffLabel;
    private javax.swing.JTextField SurnameField;
    private javax.swing.JLabel SurnameLabel;
    private javax.swing.JPanel background;
    // End of variables declaration//GEN-END:variables
}
