/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomeAffairsPackage;

/**
 *
 * @author byronkraus
 */
public class EditStaffMember2 extends javax.swing.JFrame {
    private static String id;
    /**
     * Creates new form ImageDisplay
     * @param id
     */
    public EditStaffMember2(String id) {
        this.id = id;
        enter();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        BlackBorder = new javax.swing.JPanel();
        HomeAffairsLabel = new javax.swing.JLabel();
        FullNameLabel = new javax.swing.JLabel();
        FullNameField = new javax.swing.JTextField();
        SurnameLabel = new javax.swing.JLabel();
        SurnameField = new javax.swing.JTextField();
        EditDetailsLabel = new javax.swing.JLabel();
        ExplanationLabel = new javax.swing.JLabel();
        ExplanatonLabel2 = new javax.swing.JLabel();
        ContinueButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        MiddleNameField = new javax.swing.JTextField();
        MiddleNameLabel = new javax.swing.JLabel();
        BackgroundImage = new javax.swing.JLabel();
        FullNameCheckBox = new javax.swing.JCheckBox();
        MiddleNameCheckBox = new javax.swing.JCheckBox();
        SurnameCheckBox = new javax.swing.JCheckBox();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        LogOutMenu = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setOpaque(false);
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BlackBorder.setBackground(new java.awt.Color(0, 0, 0));

        HomeAffairsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        HomeAffairsLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeAffairsLabel.setText("Home Affairs Online");

        javax.swing.GroupLayout BlackBorderLayout = new javax.swing.GroupLayout(BlackBorder);
        BlackBorder.setLayout(BlackBorderLayout);
        BlackBorderLayout.setHorizontalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeAffairsLabel)
                .addGap(166, 166, 166))
        );
        BlackBorderLayout.setVerticalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(HomeAffairsLabel)
                .addContainerGap())
        );

        Background.add(BlackBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 566, -1));

        FullNameLabel.setText("Enter your full name");
        Background.add(FullNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        FullNameField.setText("John");
        FullNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FullNameFieldFocusGained(evt);
            }
        });
        Background.add(FullNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 200, -1));

        SurnameLabel.setText("Enter your Surname");
        Background.add(SurnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 170, -1, -1));

        SurnameField.setText("Williamson");
        SurnameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SurnameFieldFocusGained(evt);
            }
        });
        Background.add(SurnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 170, 200, -1));

        EditDetailsLabel.setText("Edit the details of a Staff Member");
        Background.add(EditDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 310, -1, -1));

        ExplanationLabel.setText("Correct the incorrect details of your/ the users name, surname and/or ID and click the ");
        Background.add(ExplanationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 232, -1, -1));

        ExplanatonLabel2.setText("corresponding round button to change it.");
        Background.add(ExplanatonLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 254, -1, -1));

        ContinueButton.setText("CONTINUE");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });
        Background.add(ContinueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(443, 283, 100, 40));

        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        Background.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 283, 90, 40));

        MiddleNameField.setText("James");
        MiddleNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MiddleNameFieldFocusGained(evt);
            }
        });
        Background.add(MiddleNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 200, -1));

        MiddleNameLabel.setText("Enter your middle name");
        Background.add(MiddleNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/view/images/Picture 2.png"))); // NOI18N
        Background.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 570, 280));
        Background.add(FullNameCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));
        Background.add(MiddleNameCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));
        Background.add(SurnameCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        FileMenu.setText("File");

        LogOutMenu.setText("Log Out");
        LogOutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutMenuActionPerformed(evt);
            }
        });
        FileMenu.add(LogOutMenu);

        HelpMenu.setText("Help");
        HelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpMenuActionPerformed(evt);
            }
        });
        FileMenu.add(HelpMenu);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(571, 384));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    // Screen changes once the back button is clicked
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        EditStaffMember eng = new EditStaffMember();
        eng.setVisible(true);   
    }//GEN-LAST:event_BackButtonActionPerformed

    // Screen changes once the log out button is clicked
    private void LogOutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutMenuActionPerformed
        this.dispose();
        WelcomeScreen eng = new WelcomeScreen();
        eng.setVisible(true); 
    }//GEN-LAST:event_LogOutMenuActionPerformed

    // Screen changes once the continue button is clicked
    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        StaffManager sm = new StaffManager();
        if(FullNameCheckBox.isSelected()) {
            sm.getStaff(id).setFirstName(FullNameField.getText());
            sm.setName(FullNameField.getText(), id);
        }
        if(MiddleNameCheckBox.isSelected()) {
            sm.getStaff(id).setMiddleName(MiddleNameField.getText());
            sm.setMiddleName(MiddleNameField.getText(), id);
        }
        if(SurnameCheckBox.isSelected()) {
            sm.getStaff(id).setSurname(SurnameField.getText());
            sm.setSurname(SurnameField.getText(), id);
        }
        
        this.dispose();
        ActionPerformedScreen eng = new ActionPerformedScreen();
        eng.setVisible(true);       
    }//GEN-LAST:event_ContinueButtonActionPerformed

    private void FullNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FullNameFieldFocusGained
        //no action
    }//GEN-LAST:event_FullNameFieldFocusGained

    private void MiddleNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MiddleNameFieldFocusGained
        //no action
    }//GEN-LAST:event_MiddleNameFieldFocusGained

    private void SurnameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SurnameFieldFocusGained
        //no action
    }//GEN-LAST:event_SurnameFieldFocusGained

    //accesses internet site for help
    private void HelpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpMenuActionPerformed
        try {
            String url = "https://skaterbyron.wixsite.com/homeaffairsonlinehel";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_HelpMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStaffMember2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStaffMember2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStaffMember2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStaffMember2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStaffMember2(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel BlackBorder;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JLabel EditDetailsLabel;
    private javax.swing.JLabel ExplanationLabel;
    private javax.swing.JLabel ExplanatonLabel2;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JCheckBox FullNameCheckBox;
    private javax.swing.JTextField FullNameField;
    private javax.swing.JLabel FullNameLabel;
    private javax.swing.JMenuItem HelpMenu;
    private javax.swing.JLabel HomeAffairsLabel;
    private javax.swing.JMenuItem LogOutMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JCheckBox MiddleNameCheckBox;
    private javax.swing.JTextField MiddleNameField;
    private javax.swing.JLabel MiddleNameLabel;
    private javax.swing.JCheckBox SurnameCheckBox;
    private javax.swing.JTextField SurnameField;
    private javax.swing.JLabel SurnameLabel;
    // End of variables declaration//GEN-END:variables

    private void enter() {
        StaffManager sm = new StaffManager();
        
        FullNameField.setText(sm.getStaff(id).getFirstName());
        MiddleNameField.setText(sm.getStaff(id).getMiddleName());
        SurnameField.setText(sm.getStaff(id).getSurname());
    }
}
