/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomeAffairsPackage;

import java.awt.Color;

/**
 *
 * @author byronkraus
 */
public class EditDetails extends javax.swing.JFrame {

    /**
     * Creates new form ImageDisplay
     */
    public EditDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        BlackBorder = new javax.swing.JPanel();
        HomeAffairsLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        EditDetailsLabel = new javax.swing.JLabel();
        ContinueButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        ImageBackground = new javax.swing.JLabel();
        IncorrectIDLabel = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        LogOutMenu = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setOpaque(false);
        Background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackgroundMouseClicked(evt);
            }
        });
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BlackBorder.setBackground(new java.awt.Color(0, 0, 0));

        HomeAffairsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        HomeAffairsLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeAffairsLabel.setText("Home Affairs Online");

        javax.swing.GroupLayout BlackBorderLayout = new javax.swing.GroupLayout(BlackBorder);
        BlackBorder.setLayout(BlackBorderLayout);
        BlackBorderLayout.setHorizontalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeAffairsLabel)
                .addGap(166, 166, 166))
        );
        BlackBorderLayout.setVerticalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(HomeAffairsLabel)
                .addContainerGap())
        );

        Background.add(BlackBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 567, -1));

        IDLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IDLabel.setText("Enter your ID");
        Background.add(IDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 142, -1, -1));

        IDField.setForeground(new java.awt.Color(204, 204, 204));
        IDField.setText("6801023487265");
        IDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDFieldFocusLost(evt);
            }
        });
        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });
        Background.add(IDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 200, -1));

        EditDetailsLabel.setText("Edit the details of your booking");
        Background.add(EditDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        ContinueButton.setText("CONTINUE");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });
        Background.add(ContinueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 90, 40));

        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        Background.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 270, 90, 40));

        ImageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/view/images/Picture 2.png"))); // NOI18N
        ImageBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ImageBackgroundMouseClicked(evt);
            }
        });
        Background.add(ImageBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 570, 250));
        Background.add(IncorrectIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, -1, -1));

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        FileMenu.setText("File");

        LogOutMenu.setText("Log Out");
        LogOutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutMenuActionPerformed(evt);
            }
        });
        FileMenu.add(LogOutMenu);

        HelpMenu.setText("Help");
        HelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpMenuActionPerformed(evt);
            }
        });
        FileMenu.add(HelpMenu);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        setSize(new java.awt.Dimension(567, 368));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
        //no action
    }//GEN-LAST:event_IDFieldActionPerformed

    // Screen changes once the back button is clicked
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        UserHomeScreen eng = new UserHomeScreen();
        eng.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    // Screen changes once the continue button is clicked
    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        ApplicantManager am = new ApplicantManager();
        int pos = am.checkApplicantID(IDField.getText());
        if (pos != -1) {
            this.dispose();
            EditDetails2 eng = new EditDetails2(IDField.getText());
            eng.setVisible(true);
        } else {
            IncorrectIDLabel.setText("Incorrect ID");
            IncorrectIDLabel.setForeground(Color.red);
        }
    }//GEN-LAST:event_ContinueButtonActionPerformed

    // Screen changes once the log out button is clicked
    private void LogOutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutMenuActionPerformed
        this.dispose();
        WelcomeScreen eng = new WelcomeScreen();
        eng.setVisible(true);
    }//GEN-LAST:event_LogOutMenuActionPerformed

    //removes example data
    private void IDFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusGained
        if (IDField.getText().equalsIgnoreCase("6801023487265")) {
            IDField.setForeground(Color.black);
            IDField.setText("");
        }
    }//GEN-LAST:event_IDFieldFocusGained

    //replaces incorrect code with example data
    private void IDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusLost
        if (IDField.getText().equalsIgnoreCase("")
                || !(IDField.getText().matches("\\d+"))
                || IDField.getText().length() != 13) {

            IDField.setForeground(new Color(204, 204, 204));
            IDField.setText("6801023487265");
        }
    }//GEN-LAST:event_IDFieldFocusLost

    private void ImageBackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ImageBackgroundMouseClicked
        //no action
    }//GEN-LAST:event_ImageBackgroundMouseClicked

    private void BackgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackgroundMouseClicked
        //no action
    }//GEN-LAST:event_BackgroundMouseClicked

    //accesses internet site for help
    private void HelpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpMenuActionPerformed
        try {
            String url = "https://skaterbyron.wixsite.com/homeaffairsonlinehel";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_HelpMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting 
        //code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the 
        default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing
        /lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : 
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDetails.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDetails.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDetails.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDetails.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Background;
    private javax.swing.JPanel BlackBorder;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JLabel EditDetailsLabel;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem HelpMenu;
    private javax.swing.JLabel HomeAffairsLabel;
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel ImageBackground;
    private javax.swing.JLabel IncorrectIDLabel;
    private javax.swing.JMenuItem LogOutMenu;
    private javax.swing.JMenuBar MenuBar;
    // End of variables declaration//GEN-END:variables
}
