/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomeAffairsPackage;

/**
 *
 * @author byronkraus
 */
public class EditDetails2 extends javax.swing.JFrame {

    private static String id;

    /**
     * Creates new form ImageDisplay
     * @param id
     */
    public EditDetails2(String id) {
        this.id = id;//instantiates field
        update();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        BlackBorder = new javax.swing.JPanel();
        HomeAffairsLabel = new javax.swing.JLabel();
        SurnameLabel = new javax.swing.JLabel();
        EditDetailsLabel = new javax.swing.JLabel();
        explanationLabel = new javax.swing.JLabel();
        explanationLabel2 = new javax.swing.JLabel();
        ContinueButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        MiddleNameLabel = new javax.swing.JLabel();
        middleNameField = new javax.swing.JTextField();
        FullNameLabel = new javax.swing.JLabel();
        FullNameField = new javax.swing.JTextField();
        surnameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        EmailLabel = new javax.swing.JLabel();
        CellNumberLabel = new javax.swing.JLabel();
        cellNumberField = new javax.swing.JTextField();
        ImageBackground = new javax.swing.JLabel();
        FullNameCheckBox = new javax.swing.JCheckBox();
        MiddleNameCheckbox = new javax.swing.JCheckBox();
        CellNumberCheckBox = new javax.swing.JCheckBox();
        EmailCheckBox = new javax.swing.JCheckBox();
        SurnameCheckBox = new javax.swing.JCheckBox();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        LogOutMenu = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Background.setOpaque(false);
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BlackBorder.setBackground(new java.awt.Color(0, 0, 0));

        HomeAffairsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        HomeAffairsLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeAffairsLabel.setText("Home Affairs Online");

        javax.swing.GroupLayout BlackBorderLayout = new javax.swing.GroupLayout(BlackBorder);
        BlackBorder.setLayout(BlackBorderLayout);
        BlackBorderLayout.setHorizontalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeAffairsLabel)
                .addGap(166, 166, 166))
        );
        BlackBorderLayout.setVerticalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(HomeAffairsLabel)
                .addContainerGap())
        );

        Background.add(BlackBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 566, -1));

        SurnameLabel.setText("Enter your Surname");
        Background.add(SurnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 155, -1, -1));

        EditDetailsLabel.setText("Edit a user's details");
        Background.add(EditDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 300, -1, -1));

        explanationLabel.setText("Correct the incorrect details of your/ the users name, surname and/or ID and click the ");
        Background.add(explanationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 240, -1, -1));

        explanationLabel2.setText("corresponding round button to change it.");
        Background.add(explanationLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 255, -1, -1));

        ContinueButton.setText("CONTINUE");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });
        Background.add(ContinueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 120, 40));

        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        Background.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 100, 40));

        MiddleNameLabel.setText("Enter your middle name");
        Background.add(MiddleNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 130, -1, -1));

        middleNameField.setText("Fredrick");
        middleNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                middleNameFieldFocusGained(evt);
            }
        });
        Background.add(middleNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 200, -1));

        FullNameLabel.setText("Enter your full name");
        Background.add(FullNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 105, -1, -1));

        FullNameField.setText("John");
        FullNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FullNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FullNameFieldFocusLost(evt);
            }
        });
        FullNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullNameFieldActionPerformed(evt);
            }
        });
        Background.add(FullNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 105, 200, -1));

        surnameField.setText("Williamson");
        surnameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                surnameFieldFocusGained(evt);
            }
        });
        Background.add(surnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 155, 200, -1));

        emailField.setText("gregJones@mweb.co.za");
        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        Background.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 205, 200, -1));

        EmailLabel.setText("Enter your email");
        Background.add(EmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 205, -1, -1));

        CellNumberLabel.setText("Enter your cell number");
        Background.add(CellNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 180, -1, -1));

        cellNumberField.setText("0721553608");
        cellNumberField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cellNumberFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cellNumberFieldFocusLost(evt);
            }
        });
        cellNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellNumberFieldActionPerformed(evt);
            }
        });
        Background.add(cellNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 200, -1));

        ImageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/view/images/Picture 2.png"))); // NOI18N
        Background.add(ImageBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 560, 250));

        FullNameCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullNameCheckBoxActionPerformed(evt);
            }
        });
        Background.add(FullNameCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 105, -1, -1));

        MiddleNameCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MiddleNameCheckboxActionPerformed(evt);
            }
        });
        Background.add(MiddleNameCheckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 130, -1, -1));
        Background.add(CellNumberCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 180, -1, -1));
        Background.add(EmailCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 205, -1, -1));
        Background.add(SurnameCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 155, -1, -1));

        getContentPane().add(Background);
        Background.setBounds(1, 0, 566, 320);

        FileMenu.setText("File");

        LogOutMenu.setText("Log Out");
        LogOutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutMenuActionPerformed(evt);
            }
        });
        FileMenu.add(LogOutMenu);

        HelpMenu.setText("Help");
        HelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpMenuActionPerformed(evt);
            }
        });
        FileMenu.add(HelpMenu);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        setSize(new java.awt.Dimension(569, 370));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Screen changes once the back button is clicked
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        EditDetails eng = new EditDetails();
        eng.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    // Screen changes once the continue button is clicked and updates database
    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        ApplicantManager am = new ApplicantManager();
        //each option is checked and changed values are updated
        if (FullNameCheckBox.isSelected()) {
            am.getApplicant(id).setFirstName(FullNameField.getText());
            am.setName(FullNameField.getText(), id);
        }
        if (MiddleNameCheckbox.isSelected()) {
            am.getApplicant(id).setMiddleName(middleNameField.getText());
            am.setMiddleName(middleNameField.getText(), id);
        }
        if (SurnameCheckBox.isSelected()) {
            am.getApplicant(id).setSurname(surnameField.getText());
            am.setSurname(surnameField.getText(), id);
        }
        if (CellNumberCheckBox.isSelected()) {
            am.getApplicant(id).setCellNumber(cellNumberField.getText());
            am.setCellNumber(cellNumberField.getText(), id);
        }
        if (EmailCheckBox.isSelected()) {
            am.getApplicant(id).setEmail(emailField.getText());
            am.setEmail(emailField.getText(), id);
        }

        new ActionPerformedScreen().setVisible(true);
    }//GEN-LAST:event_ContinueButtonActionPerformed

    // Screen changes once the log out button is clicked
    private void LogOutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutMenuActionPerformed
        this.dispose();
        WelcomeScreen eng = new WelcomeScreen();
        eng.setVisible(true);
    }//GEN-LAST:event_LogOutMenuActionPerformed

    private void cellNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellNumberFieldActionPerformed
        //no action
    }//GEN-LAST:event_cellNumberFieldActionPerformed

    private void FullNameCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullNameCheckBoxActionPerformed
        //no action
    }//GEN-LAST:event_FullNameCheckBoxActionPerformed

    private void MiddleNameCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MiddleNameCheckboxActionPerformed
        //no action
    }//GEN-LAST:event_MiddleNameCheckboxActionPerformed

    private void FullNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullNameFieldActionPerformed
        //no action
    }//GEN-LAST:event_FullNameFieldActionPerformed

    private void FullNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FullNameFieldFocusGained
        //no action
    }//GEN-LAST:event_FullNameFieldFocusGained

    private void middleNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_middleNameFieldFocusGained
        //no action
    }//GEN-LAST:event_middleNameFieldFocusGained

    private void surnameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_surnameFieldFocusGained
        //no action
    }//GEN-LAST:event_surnameFieldFocusGained

    private void cellNumberFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cellNumberFieldFocusGained
        //no action
    }//GEN-LAST:event_cellNumberFieldFocusGained

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        //no action
    }//GEN-LAST:event_emailFieldFocusGained

    private void FullNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FullNameFieldFocusLost
        //no action
    }//GEN-LAST:event_FullNameFieldFocusLost

    //checks the new data
    private void cellNumberFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cellNumberFieldFocusLost
        ApplicantManager am = new ApplicantManager();
        if (cellNumberField.getText().length() != 10 
                || !(cellNumberField.getText().matches("\\d+")) 
                || cellNumberField.getText().charAt(0) != '0') {
            
            cellNumberField.setText(am.getApplicant(id).getCellNumber());
        }
    }//GEN-LAST:event_cellNumberFieldFocusLost

    //checks the new data
    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        ApplicantManager am = new ApplicantManager();
        if ((emailField.getText().compareTo("@") > 1) 
                || !(emailField.getText().compareTo(".") > 1)) {
           
            emailField.setText(am.getApplicant(id).getEmail());
        }
    }//GEN-LAST:event_emailFieldFocusLost

    //accesses internet site for help
    private void HelpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpMenuActionPerformed
        try {
            String url = "https://skaterbyron.wixsite.com/homeaffairsonlinehel";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_HelpMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditDetails2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditDetails2(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Background;
    private javax.swing.JPanel BlackBorder;
    private javax.swing.JCheckBox CellNumberCheckBox;
    private javax.swing.JLabel CellNumberLabel;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JLabel EditDetailsLabel;
    private javax.swing.JCheckBox EmailCheckBox;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JCheckBox FullNameCheckBox;
    private javax.swing.JTextField FullNameField;
    private javax.swing.JLabel FullNameLabel;
    private javax.swing.JMenuItem HelpMenu;
    private javax.swing.JLabel HomeAffairsLabel;
    private javax.swing.JLabel ImageBackground;
    private javax.swing.JMenuItem LogOutMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JCheckBox MiddleNameCheckbox;
    private javax.swing.JLabel MiddleNameLabel;
    private javax.swing.JCheckBox SurnameCheckBox;
    private javax.swing.JLabel SurnameLabel;
    private javax.swing.JTextField cellNumberField;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel explanationLabel;
    private javax.swing.JLabel explanationLabel2;
    private javax.swing.JTextField middleNameField;
    private javax.swing.JTextField surnameField;
    // End of variables declaration//GEN-END:variables

    private void update() {
         ApplicantManager am = new ApplicantManager();
         
         FullNameField.setText(am.getApplicant(id).getFirstName());
         middleNameField.setText(am.getApplicant(id).getMiddleName());
         surnameField.setText(am.getApplicant(id).getSurname());
         cellNumberField.setText(am.getApplicant(id).getCellNumber());
         emailField.setText(am.getApplicant(id).getEmail());
    }
}
