/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomeAffairsPackage;

import java.awt.Color;

/**
 *
 * @author byronkraus
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form ImageDisplay
     */
    public LoginScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        BlackBorder = new javax.swing.JPanel();
        HomeAffairsLabel = new javax.swing.JLabel();
        IncorrectLabel = new javax.swing.JLabel();
        EnterDetailsLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        PasswordLabel = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setOpaque(false);
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BlackBorder.setBackground(new java.awt.Color(0, 0, 0));

        HomeAffairsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        HomeAffairsLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeAffairsLabel.setText("Home Affairs Online");

        javax.swing.GroupLayout BlackBorderLayout = new javax.swing.GroupLayout(BlackBorder);
        BlackBorder.setLayout(BlackBorderLayout);
        BlackBorderLayout.setHorizontalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IncorrectLabel)
                    .addComponent(HomeAffairsLabel))
                .addGap(166, 166, 166))
        );
        BlackBorderLayout.setVerticalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IncorrectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeAffairsLabel)
                .addContainerGap())
        );

        Background.add(BlackBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        EnterDetailsLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        EnterDetailsLabel.setText("Enter your login details:");
        Background.add(EnterDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 81, -1, -1));

        IDLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IDLabel.setText("ID number");
        Background.add(IDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 121, -1, -1));

        PasswordLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PasswordLabel.setText("Password");
        Background.add(PasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 166, -1, -1));

        UsernameField.setForeground(new java.awt.Color(204, 204, 204));
        UsernameField.setText("0201125085088");
        UsernameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                UsernameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsernameFieldFocusLost(evt);
            }
        });
        UsernameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsernameFieldMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UsernameFieldMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                UsernameFieldMouseExited(evt);
            }
        });
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });
        Background.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 121, 117, -1));

        PasswordField.setForeground(new java.awt.Color(204, 204, 204));
        PasswordField.setText("Test123");
        PasswordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PasswordFieldFocusLost(evt);
            }
        });
        PasswordField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordFieldMouseClicked(evt);
            }
        });
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });
        Background.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 165, 117, -1));

        LoginButton.setText("LOGIN");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        Background.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 256, 100, 40));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/view/images/Picture 2.png"))); // NOI18N
        Background.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 560, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(566, 342));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        //no action
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        //no action
    }//GEN-LAST:event_PasswordFieldActionPerformed

    // Screen changes once the login button is clicked
    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        String password = String.valueOf(PasswordField.getPassword());
        ApplicantManager am = new ApplicantManager();
        int pos = am.checkApplicantID(UsernameField.getText());
        StaffManager sm = new StaffManager();
        int pos2 = sm.checkStaffID(UsernameField.getText());
        
        if (pos != -1 && am.checkApplicantPassword(pos, password)) {

            this.dispose();
            UserHomeScreen eng = new UserHomeScreen();
            eng.setVisible(true);
        } else if (pos2 != -1 && sm.checkStaffPassword(pos, password)
                && sm.checkRole(pos2).equals("1")) {

            this.dispose();
            StaffHomeScreen2 eng = new StaffHomeScreen2();
            eng.setVisible(true);
        } else if (pos2 != -1 && sm.checkStaffPassword(pos, password)
                && sm.checkRole(pos2).equals("2")) {

            this.dispose();
            AdministratorHomeScreen eng = new AdministratorHomeScreen();
            eng.setVisible(true);
        } else {
            IncorrectLabel.setText
        ("Incorrect ID or password. Please try again");
            IncorrectLabel.setForeground(Color.red);
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void UsernameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameFieldMouseClicked
        //no action
    }//GEN-LAST:event_UsernameFieldMouseClicked

    private void UsernameFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameFieldMouseExited
        //no action
    }//GEN-LAST:event_UsernameFieldMouseExited

    private void UsernameFieldMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsernameFieldMouseEntered
        //no action
    }//GEN-LAST:event_UsernameFieldMouseEntered

    private void PasswordFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordFieldMouseClicked
        //no action
    }//GEN-LAST:event_PasswordFieldMouseClicked

    // Removes example data
    private void UsernameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFieldFocusGained
        if (UsernameField.getText().equalsIgnoreCase("0201125085088")) {
            UsernameField.setForeground(Color.black);
            UsernameField.setText("");
        }
    }//GEN-LAST:event_UsernameFieldFocusGained

    // puts example data if incorrect data is inputted
    private void UsernameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsernameFieldFocusLost
        if (UsernameField.getText().equalsIgnoreCase("")
                || !(UsernameField.getText().matches("\\d+"))
                || UsernameField.getText().length() != 13) {

            UsernameField.setForeground(new Color(204, 204, 204));
            UsernameField.setText("0201125085088");
        }
    }//GEN-LAST:event_UsernameFieldFocusLost

    // removes example data
    private void PasswordFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusGained
        String password = String.valueOf(PasswordField.getPassword());

        if (password.equalsIgnoreCase("Test123")) {
            PasswordField.setForeground(Color.black);
            PasswordField.setText("");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldFocusGained

    // puts example data if incorrect data is inputted
    private void PasswordFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PasswordFieldFocusLost
        String password = String.valueOf(PasswordField.getPassword());

        if (password.equalsIgnoreCase("")) {
            PasswordField.setForeground(new Color(204, 204, 204));
            PasswordField.setText("Test123");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel BlackBorder;
    private javax.swing.JLabel EnterDetailsLabel;
    private javax.swing.JLabel HomeAffairsLabel;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel IncorrectLabel;
    private javax.swing.JButton LoginButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JTextField UsernameField;
    // End of variables declaration//GEN-END:variables
}
