/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomeAffairsPackage;

import java.awt.Color;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author byronkraus
 */
public class Passport2 extends javax.swing.JFrame {
    private static String ID, FullName, Surname;

    /**
     * Creates new form ImageDisplay
     * @param ID
     * @param FullName
     * @param Surname
     */
    public Passport2(String ID, String FullName, String Surname) {
        this.ID = ID;
        this.FullName = FullName;
        this.Surname = Surname;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        BlackBorder = new javax.swing.JPanel();
        HomeAffairsLabel = new javax.swing.JLabel();
        Errorlabel = new javax.swing.JLabel();
        PhotoIDLabel = new javax.swing.JLabel();
        BookingPassportLabel = new javax.swing.JLabel();
        ContinueButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        UploadButton = new javax.swing.JButton();
        BackgroundImage = new javax.swing.JLabel();
        PhotoDirectoryPane = new javax.swing.JScrollPane();
        PhotoDirectoryLabel = new javax.swing.JTextPane();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        LogOutMenu = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setOpaque(false);
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BlackBorder.setBackground(new java.awt.Color(0, 0, 0));

        HomeAffairsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        HomeAffairsLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeAffairsLabel.setText("Home Affairs Online");
        HomeAffairsLabel.setToolTipText("");

        javax.swing.GroupLayout BlackBorderLayout = new javax.swing.GroupLayout(BlackBorder);
        BlackBorder.setLayout(BlackBorderLayout);
        BlackBorderLayout.setHorizontalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Errorlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HomeAffairsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(166, 166, 166))
        );
        BlackBorderLayout.setVerticalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addComponent(Errorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeAffairsLabel)
                .addContainerGap())
        );

        Background.add(BlackBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, -1));

        PhotoIDLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        PhotoIDLabel.setText("Photo of Certified copy of ID");
        Background.add(PhotoIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        BookingPassportLabel.setText("Booking your Passport Renewal");
        Background.add(BookingPassportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        ContinueButton.setText("CONTINUE");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });
        Background.add(ContinueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 265, 90, 40));

        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        Background.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 265, 90, 40));

        UploadButton.setText("UPLOAD");
        UploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadButtonActionPerformed(evt);
            }
        });
        Background.add(UploadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 90, 40));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/view/images/Picture 2.png"))); // NOI18N
        Background.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 560, 260));

        PhotoDirectoryLabel.setEditable(false);
        PhotoDirectoryLabel.setText("Photo's directory will appear here once uploaded");
        PhotoDirectoryPane.setViewportView(PhotoDirectoryLabel);

        Background.add(PhotoDirectoryPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 200, 80));

        FileMenu.setText("File");

        LogOutMenu.setText("Log Out");
        LogOutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutMenuActionPerformed(evt);
            }
        });
        FileMenu.add(LogOutMenu);

        HelpMenu.setText("Help");
        HelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpMenuActionPerformed(evt);
            }
        });
        FileMenu.add(HelpMenu);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(561, 365));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Screen changes once the back button is clicked
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        Passport eng = new Passport();
        eng.setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    // Screen changes once the continue button is clicked
    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        if(!(F == null)) {
        this.dispose();
        SelectBooking eng = new SelectBooking("Passport", ID, FullName, Surname
                , Image, "2");
        eng.setVisible(true);
        } else {
            Errorlabel.setText("Please upload a file");
            Errorlabel.setForeground(Color.red);
        }
    }//GEN-LAST:event_ContinueButtonActionPerformed

    // Screen changes once the log out button is clicked
    private void LogOutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutMenuActionPerformed
        this.dispose();
        WelcomeScreen eng = new WelcomeScreen();
        eng.setVisible(true);
    }//GEN-LAST:event_LogOutMenuActionPerformed

    //user can upload their photo into the database
    private void UploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadButtonActionPerformed
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Image Files", "jpg", "png", "jpeg");
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(filter);
        chooser.showOpenDialog(null);
        F = chooser.getSelectedFile();
        String FileName = F.getAbsolutePath();
        Image = new ImageIcon(FileName);
        PhotoDirectoryLabel.setText(F.getAbsolutePath());
    }//GEN-LAST:event_UploadButtonActionPerformed

    //accesses internet site for help
    private void HelpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpMenuActionPerformed
        try {
            String url = "https://skaterbyron.wixsite.com/homeaffairsonlinehel";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_HelpMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passport2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passport2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passport2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passport2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Passport2(ID, FullName, Surname).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel BlackBorder;
    private javax.swing.JLabel BookingPassportLabel;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JLabel Errorlabel;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem HelpMenu;
    private javax.swing.JLabel HomeAffairsLabel;
    private javax.swing.JMenuItem LogOutMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTextPane PhotoDirectoryLabel;
    private javax.swing.JScrollPane PhotoDirectoryPane;
    private javax.swing.JLabel PhotoIDLabel;
    private javax.swing.JButton UploadButton;
    // End of variables declaration//GEN-END:variables
File F = null;
ImageIcon Image = null;
}
