/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomeAffairsPackage;

import java.awt.Color;

/**
 *
 * @author byronkraus
 */
public class RetrieveInfo2 extends javax.swing.JFrame {

    private static String Type;

    /**
     * Creates new form ImageDisplay
     */
    public RetrieveInfo2(String Type) {
        Type = this.Type;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        BlackBorder = new javax.swing.JPanel();
        HomeAffairsLabel = new javax.swing.JLabel();
        IncorrectLabel = new javax.swing.JLabel();
        RetrieveInfoLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        ContinueButton = new javax.swing.JButton();
        BackgroundImage = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        LogOutMenu = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setOpaque(false);
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BlackBorder.setBackground(new java.awt.Color(0, 0, 0));

        HomeAffairsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        HomeAffairsLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeAffairsLabel.setText("Home Affairs Online");

        IncorrectLabel.setText("jLabel1");

        javax.swing.GroupLayout BlackBorderLayout = new javax.swing.GroupLayout(BlackBorder);
        BlackBorder.setLayout(BlackBorderLayout);
        BlackBorderLayout.setHorizontalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(IncorrectLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HomeAffairsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(166, 166, 166))
        );
        BlackBorderLayout.setVerticalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IncorrectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomeAffairsLabel)
                .addContainerGap())
        );

        Background.add(BlackBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 566, -1));

        RetrieveInfoLabel.setText("Retrieve information of booking");
        Background.add(RetrieveInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, -1, -1));

        IDLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IDLabel.setText("Enter your ID");
        Background.add(IDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 136, -1, -1));

        IDField.setForeground(new java.awt.Color(204, 204, 204));
        IDField.setText("6801023487265");
        IDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDFieldFocusLost(evt);
            }
        });
        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });
        Background.add(IDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 164, 200, -1));

        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        Background.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 275, 100, 40));

        ContinueButton.setText("CONTINUE");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });
        Background.add(ContinueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 275, 100, 40));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/view/images/Picture 2.png"))); // NOI18N
        Background.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 560, 270));

        FileMenu.setText("File");

        LogOutMenu.setText("Log Out");
        LogOutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutMenuActionPerformed(evt);
            }
        });
        FileMenu.add(LogOutMenu);

        HelpMenu.setText("Help");
        HelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpMenuActionPerformed(evt);
            }
        });
        FileMenu.add(HelpMenu);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        setSize(new java.awt.Dimension(566, 377));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
        //no action
    }//GEN-LAST:event_IDFieldActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        RetrieveInfo eng = new RetrieveInfo();
        eng.setVisible(true);//changes the screen when the back button is clicked
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        ApplicantManager am = new ApplicantManager();
        int pos = am.checkApplicantID(IDField.getText());
        
        if (pos != -1) {
            if (Type.equalsIgnoreCase("SmartID")) {
                //changes the screen when the continue button is clicked
                this.dispose();
                RetrieveInfoSmartID eng = new 
                RetrieveInfoSmartID(IDField.getText());
                eng.setVisible(true);
            } else {
                if (Type.equalsIgnoreCase("Passport")) {
                    //changes the screen when the continue button is clicked
                    this.dispose();
                    RetrieveInfoPassport eng = new 
                    RetrieveInfoPassport(IDField.getText());
                    eng.setVisible(true);
                } else {
                    if (Type.equalsIgnoreCase("UnabridgedBirthCertificate")) {
                        //changes the screen when the continue button is clicked
                        this.dispose();
                        RetrieveInfoUnabridgedBirthCertificate eng = new 
                        RetrieveInfoUnabridgedBirthCertificate(IDField.getText());
                        eng.setVisible(true);
                    } else {
                        IncorrectLabel.setText("Booking Type not selected");
                        IncorrectLabel.setForeground(Color.red);
                    }

                }
            }
        } else {
            IncorrectLabel.setText("Incorrect ID");
            IncorrectLabel.setForeground(Color.red);
        }
    }//GEN-LAST:event_ContinueButtonActionPerformed

    private void LogOutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutMenuActionPerformed
        this.dispose();
        WelcomeScreen eng = new WelcomeScreen();
        eng.setVisible(true);
        //changes the screen when the log out button is clicked
    }//GEN-LAST:event_LogOutMenuActionPerformed

    //removes the example data
    private void IDFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusGained
        if (IDField.getText().equalsIgnoreCase("6801023487265")) {
            IDField.setForeground(Color.black);
            IDField.setText("");
        }
    }//GEN-LAST:event_IDFieldFocusGained

    //changes the incorrect data to example data
    private void IDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusLost
        if (IDField.getText().equalsIgnoreCase("")
                || !(IDField.getText().matches("\\d+"))
                || IDField.getText().length() != 13) {

            IDField.setForeground(new Color(204, 204, 204));
            IDField.setText("6801023487265");
        }
    }//GEN-LAST:event_IDFieldFocusLost

    //accesses internet site for help
    private void HelpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpMenuActionPerformed
        try {
            String url = "https://skaterbyron.wixsite.com/homeaffairsonlinehel";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_HelpMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RetrieveInfo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RetrieveInfo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RetrieveInfo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RetrieveInfo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RetrieveInfo2(Type).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel BlackBorder;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem HelpMenu;
    private javax.swing.JLabel HomeAffairsLabel;
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel IncorrectLabel;
    private javax.swing.JMenuItem LogOutMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel RetrieveInfoLabel;
    // End of variables declaration//GEN-END:variables
}
