/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomeAffairsPackage;

import java.awt.Image;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;

/**
 *
 * @author byronkraus
 */
public class SelectBooking extends javax.swing.JFrame {

    //instantiates fields
    private static String Type, ID, FullName, Surname;
    private static ImageIcon CopyID, Passport, ParentID, BirthCertificate,
            ProofOfResidence;

    /**
     * Creates new form ImageDisplay
     */
    public SelectBooking(String Passport, String ID, String FullName,
            String Surname, ImageIcon CopyID) {
        //assigns values to fields
        Type = Passport;
        this.ID = ID;
        this.FullName = FullName;
        this.Surname = Surname;
        this.CopyID = CopyID;
        ParentID = null;
        Display();
        initComponents();
    }

    public SelectBooking(String SmartID, String ID, String FullName,
            String Surname, ImageIcon Passport, ImageIcon ParentID,
            ImageIcon BirthCertificate, ImageIcon ProofOfResidence) {
        //assigns values to fields
        Type = SmartID;
        this.ID = ID;
        this.FullName = FullName;
        this.Surname = Surname;
        this.Passport = Passport;
        this.ParentID = ParentID;
        this.BirthCertificate = BirthCertificate;
        this.ProofOfResidence = ProofOfResidence;
        CopyID = null;
        Display();
        initComponents();
    }

    public SelectBooking(String UnabrigedBirthCertificate, String ID,
            String FullName, String Surname, ImageIcon ParentID,
            String number) {
        //assigns values to fields
        Type = UnabrigedBirthCertificate;
        this.ID = ID;
        this.FullName = FullName;
        this.Surname = Surname;
        this.CopyID = CopyID;
        this.ParentID = ParentID;
        BirthCertificate = null;
        CopyID = null;
        Display();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        BlackBorder = new javax.swing.JPanel();
        HomeAffairsLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        SelectBookingLabel = new javax.swing.JLabel();
        SelectBookingPane = new javax.swing.JScrollPane();
        SelectBookingTable = new javax.swing.JTable();
        ContinueButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        BackgroundImage = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        LogOutMenu = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setOpaque(false);
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BlackBorder.setBackground(new java.awt.Color(0, 0, 0));

        HomeAffairsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        HomeAffairsLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeAffairsLabel.setText("Home Affairs Online");

        javax.swing.GroupLayout BlackBorderLayout = new javax.swing.GroupLayout(BlackBorder);
        BlackBorder.setLayout(BlackBorderLayout);
        BlackBorderLayout.setHorizontalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeAffairsLabel)
                .addGap(166, 166, 166))
        );
        BlackBorderLayout.setVerticalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(HomeAffairsLabel)
                .addContainerGap())
        );

        Background.add(BlackBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 546, -1));

        IDLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        IDLabel.setText("Enter your ID");
        Background.add(IDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 80, -1, -1));

        SelectBookingLabel.setText("Selecting your booking");
        Background.add(SelectBookingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 300, -1, -1));

        SelectBookingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Wed 01 April", "10:00AM"},
                {"Thu 02 April", "10:00AM"},
                {"Thu 02 April", "11:00AM"},
                {"Fri 03 April", "09:00AM"},
                {"Fri 03 April", "9:00AM"},
                {"Fri 03 April", "10:00AM"},
                {"Fri 03 April", "11:00AM"},
                {"Fri 03 April", "01:00PM"},
                {"Mon 06 April", "10:00AM"},
                {"Mon 06 April", "02:00PM"}
            },
            new String [] {
                "Date", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SelectBookingPane.setViewportView(SelectBookingTable);

        Background.add(SelectBookingPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 381, 146));

        ContinueButton.setText("CONTINUE");
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });
        Background.add(ContinueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 90, 40));

        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        Background.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 273, 100, 40));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/view/images/Picture 2.png"))); // NOI18N
        Background.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 540, 270));

        FileMenu.setText("File");
        FileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuActionPerformed(evt);
            }
        });

        LogOutMenu.setText("Log Out");
        LogOutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutMenuActionPerformed(evt);
            }
        });
        FileMenu.add(LogOutMenu);

        HelpMenu.setText("Help");
        HelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpMenuActionPerformed(evt);
            }
        });
        FileMenu.add(HelpMenu);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(546, 375));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        UserHomeScreen eng = new UserHomeScreen();
        eng.setVisible(true);
        //changes the screen when the back button is clicked
    }//GEN-LAST:event_BackButtonActionPerformed

    //adds booking to database
    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        if (BirthCertificate.equals(null) && CopyID.equals(null)) {
            UnabridgedBirthCertificatesManager um
                    = new UnabridgedBirthCertificatesManager();
            um.addUnabridgedBirthCertificate(ID, ParentID.getImage());
            
            this.dispose();
            ActionPerformedScreen eng = new ActionPerformedScreen();
            eng.setVisible(true);
            //changes the screen when the continue button is clicked
        } else {
            if (CopyID.equals(null)) {
                SmartIDManager sm = new SmartIDManager();
                sm.addSmartID(ID, ParentID.getImage(),
                        BirthCertificate.getImage(),
                        ProofOfResidence.getImage());
                
                this.dispose();
                ActionPerformedScreen eng = new ActionPerformedScreen();
                eng.setVisible(true);
                //changes the screen when the continue button is clicked
            } else {
                if (ParentID.equals(null)) {
                    PassportManager pm = new PassportManager();
                    pm.addPassport(ID, CopyID.getImage());
                   
                    this.dispose();
                    ActionPerformedScreen eng = new ActionPerformedScreen();
                    eng.setVisible(true);
                    //changes the screen when the continue button is clicked
                } else {
                    String error = "Unable to retrieve type of Booking "
                            + "(SmartID, Passport, UnabridgedBirthCertificate)";
                    ErrorScreen eng = new ErrorScreen(error);
                    eng.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_ContinueButtonActionPerformed

    private void LogOutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutMenuActionPerformed
        this.dispose();
        WelcomeScreen eng = new WelcomeScreen();
        eng.setVisible(true);
        //changes the screen when the log out button is clicked
    }//GEN-LAST:event_LogOutMenuActionPerformed

    private void FileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuActionPerformed
        //no action
    }//GEN-LAST:event_FileMenuActionPerformed

    //accesses internet site for help
    private void HelpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpMenuActionPerformed
        try {
            String url = "https://skaterbyron.wixsite.com/homeaffairsonlinehel";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_HelpMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectBooking(Type, ID, FullName, Surname, CopyID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel BlackBorder;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem HelpMenu;
    private javax.swing.JLabel HomeAffairsLabel;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JMenuItem LogOutMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel SelectBookingLabel;
    private javax.swing.JScrollPane SelectBookingPane;
    private javax.swing.JTable SelectBookingTable;
    // End of variables declaration//GEN-END:variables

    private void Display() {
        //enters the available times to be selected
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("EEE dd MMMM");
        LocalDateTime now = LocalDateTime.now();
        now = now.plusDays(3);
        String Date = dtf.format(now);
        AppointmentManager am = new AppointmentManager();
        String[] Hours = {"10:00", "11:00", "12:00", "14:00", "16:00"};
        String[] newHours = am.checkArray(Hours, Date);
        int count = 0;

        if (BirthCertificate.equals(null) && CopyID.equals(null)) {
            for (int i = 0; i < newHours.length; i++) {
                SelectBookingTable.add(Date, this);
                SelectBookingTable.add(newHours[count], this);
                count++;
            }
        } else {
            if (CopyID.equals(null)) {
                for (int i = 0; i < newHours.length; i++) {
                    SelectBookingTable.add(Date, this);
                    SelectBookingTable.add(newHours[count], this);
                    count++;
                }
            } else {
                if (ParentID.equals(null)) {
                    for (int i = 0; i < newHours.length; i++) {
                        SelectBookingTable.add(Date, this);
                        SelectBookingTable.add(newHours[count], this);
                        count++;
                    }
                } else {
                    String error = "Unable to retrieve type of Booking "
                            + "(SmartID, Passport, UnabridgedBirthCertificate)";
                    ErrorScreen eng = new ErrorScreen(error);
                    eng.setVisible(true);
                }
            }
        }
    }
}
