/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomeAffairsPackage;

import java.awt.Color;

/**
 *
 * @author byronkraus
 */
public class SmartID extends javax.swing.JFrame {

    /**
     * Creates new form ImageDisplay
     */
    public SmartID() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        BlackBorder = new javax.swing.JPanel();
        HomeAffairsLabel = new javax.swing.JLabel();
        IncorrectLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        SurnameLabel = new javax.swing.JLabel();
        SurnameField = new javax.swing.JTextField();
        BookingSmartIDLabel = new javax.swing.JLabel();
        FirstTimeApplicantLabel = new javax.swing.JLabel();
        ClickBoxCheckBox = new javax.swing.JCheckBox();
        ClickBoxLabel = new javax.swing.JLabel();
        Continue = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        BackgroundImage = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        LogOutMenu = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setOpaque(false);
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BlackBorder.setBackground(new java.awt.Color(0, 0, 0));

        HomeAffairsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        HomeAffairsLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeAffairsLabel.setText("Home Affairs Online");

        javax.swing.GroupLayout BlackBorderLayout = new javax.swing.GroupLayout(BlackBorder);
        BlackBorder.setLayout(BlackBorderLayout);
        BlackBorderLayout.setHorizontalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(HomeAffairsLabel)
                .addGap(166, 166, 166))
            .addGroup(BlackBorderLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(IncorrectLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BlackBorderLayout.setVerticalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addComponent(IncorrectLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(HomeAffairsLabel)
                .addContainerGap())
        );

        Background.add(BlackBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 546, -1));

        IDLabel.setText("Enter your ID");
        Background.add(IDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 67, -1, -1));

        IDField.setForeground(new java.awt.Color(204, 204, 204));
        IDField.setText("6801023487265");
        IDField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IDFieldFocusLost(evt);
            }
        });
        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });
        Background.add(IDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 62, 200, -1));

        FirstNameLabel.setText("Enter your first name");
        Background.add(FirstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 111, -1, -1));

        FirstNameField.setForeground(new java.awt.Color(204, 204, 204));
        FirstNameField.setText("John");
        FirstNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FirstNameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FirstNameFieldFocusLost(evt);
            }
        });
        Background.add(FirstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 106, 200, -1));

        SurnameLabel.setText("Enter your Surname");
        Background.add(SurnameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 155, -1, -1));

        SurnameField.setForeground(new java.awt.Color(204, 204, 204));
        SurnameField.setText("Williamson");
        SurnameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SurnameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SurnameFieldFocusLost(evt);
            }
        });
        Background.add(SurnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 150, 200, -1));

        BookingSmartIDLabel.setText("Booking your Smart ID");
        Background.add(BookingSmartIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        FirstTimeApplicantLabel.setText("Are you a first time applicant?");
        Background.add(FirstTimeApplicantLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 197, -1, -1));

        ClickBoxCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClickBoxCheckBoxActionPerformed(evt);
            }
        });
        Background.add(ClickBoxCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        ClickBoxLabel.setText("(Click box if yes)");
        Background.add(ClickBoxLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 219, -1, -1));

        Continue.setText("CONTINUE");
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });
        Background.add(Continue, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, 40));

        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        Background.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 98, 40));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/view/images/Picture 2.png"))); // NOI18N
        Background.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 540, 260));

        FileMenu.setText("File");
        FileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileMenuActionPerformed(evt);
            }
        });

        LogOutMenu.setText("Log Out");
        LogOutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutMenuActionPerformed(evt);
            }
        });
        FileMenu.add(LogOutMenu);

        HelpMenu.setText("Help");
        HelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpMenuActionPerformed(evt);
            }
        });
        FileMenu.add(HelpMenu);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(547, 364));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
        //no action
    }//GEN-LAST:event_IDFieldActionPerformed

    private void ClickBoxCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClickBoxCheckBoxActionPerformed
        //no action
    }//GEN-LAST:event_ClickBoxCheckBoxActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        this.dispose();
        UserHomeScreen eng = new UserHomeScreen();
        eng.setVisible(true);
        //changes the screen when the back button is clicked
    }//GEN-LAST:event_BackButtonActionPerformed

    //changes the screen when the continue button is clicked
    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed
        ApplicantManager am = new ApplicantManager();
        int pos = am.checkApplicantID(IDField.getText());
        if(am.checkApplicantID(IDField.getText()) != -1 && am.checkApplicantName
        (pos, FirstNameField.getText())){
            //checks if applicant is first time user
            if(ClickBoxCheckBox.isSelected()) {
                this.dispose();
                SmartID3 eng = new SmartID3(IDField.getText(), 
                        FirstNameField.getText(), SurnameField.getText());
                eng.setVisible(true);
            } else {
                this.dispose();
                SmartID2 eng = new SmartID2(IDField.getText(), 
                        FirstNameField.getText(), SurnameField.getText());
                eng.setVisible(true);
            }
        } else {
            IncorrectLabel.setText("Incorrect details");
            IncorrectLabel.setForeground(Color.red);
        }
    }//GEN-LAST:event_ContinueActionPerformed

    private void LogOutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutMenuActionPerformed
        this.dispose();
        WelcomeScreen eng = new WelcomeScreen();
        eng.setVisible(true);//changes when the log out button is clicked
    }//GEN-LAST:event_LogOutMenuActionPerformed

    //removes the example data
    private void IDFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusGained
        if (IDField.getText().equalsIgnoreCase("6801023487265")) {
            IDField.setForeground(Color.black);
            IDField.setText("");
        }
    }//GEN-LAST:event_IDFieldFocusGained

    //puts example data if incorrect data is inputted
    private void IDFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFieldFocusLost
        if (IDField.getText().equalsIgnoreCase("") || 
                !(IDField.getText().matches("\\d+")) || 
                IDField.getText().length() != 13) {
            
            IDField.setForeground(new Color(204, 204, 204));
            IDField.setText("6801023487265");
        }
    }//GEN-LAST:event_IDFieldFocusLost

    //removes the example data
    private void FirstNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstNameFieldFocusGained
        if (FirstNameField.getText().equalsIgnoreCase("John")) {
            FirstNameField.setForeground(Color.black);
            FirstNameField.setText("");
        }
    }//GEN-LAST:event_FirstNameFieldFocusGained

    //puts example data if incorrect data is inputted
    private void FirstNameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FirstNameFieldFocusLost
        if (FirstNameField.getText().equalsIgnoreCase("")) {
            FirstNameField.setForeground(new Color(204, 204, 204));
            FirstNameField.setText("John");
        }
    }//GEN-LAST:event_FirstNameFieldFocusLost

    //removes the example data
    private void SurnameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SurnameFieldFocusGained
        if (SurnameField.getText().equalsIgnoreCase("Williamson")) {
            SurnameField.setForeground(Color.black);
            SurnameField.setText("");
        }
    }//GEN-LAST:event_SurnameFieldFocusGained

    //puts example data if incorrect data is inputted
    private void SurnameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SurnameFieldFocusLost
        if (SurnameField.getText().equalsIgnoreCase("")) {
            SurnameField.setForeground(new Color(204, 204, 204));
            SurnameField.setText("Williamson");
        }
    }//GEN-LAST:event_SurnameFieldFocusLost

    private void FileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileMenuActionPerformed
        //no action
    }//GEN-LAST:event_FileMenuActionPerformed

    //accesses internet site for help
    private void HelpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpMenuActionPerformed
        try {
            String url = "https://skaterbyron.wixsite.com/homeaffairsonlinehel";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_HelpMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SmartID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SmartID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SmartID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SmartID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SmartID().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel BlackBorder;
    private javax.swing.JLabel BookingSmartIDLabel;
    private javax.swing.JCheckBox ClickBoxCheckBox;
    private javax.swing.JLabel ClickBoxLabel;
    private javax.swing.JButton Continue;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JLabel FirstTimeApplicantLabel;
    private javax.swing.JMenuItem HelpMenu;
    private javax.swing.JLabel HomeAffairsLabel;
    private javax.swing.JTextField IDField;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel IncorrectLabel;
    private javax.swing.JMenuItem LogOutMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JTextField SurnameField;
    private javax.swing.JLabel SurnameLabel;
    // End of variables declaration//GEN-END:variables
}
