/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HomeAffairsPackage;

/**
 *
 * @author byronkraus
 */
public class UserHomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form ImageDisplay
     */
    public UserHomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        BlackBorder = new javax.swing.JPanel();
        HomeAffairsLabel = new javax.swing.JLabel();
        BookSmartIDButton = new javax.swing.JButton();
        EditDetailsButton = new javax.swing.JButton();
        BookPassportButton = new javax.swing.JButton();
        RemoveBookingButton = new javax.swing.JButton();
        ViewBookingButton = new javax.swing.JButton();
        BookUnabridgedButton = new javax.swing.JButton();
        BackgroundImage = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        LogOutMenu = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setOpaque(false);
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BlackBorder.setBackground(new java.awt.Color(0, 0, 0));

        HomeAffairsLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        HomeAffairsLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeAffairsLabel.setText("Home Affairs Online");

        javax.swing.GroupLayout BlackBorderLayout = new javax.swing.GroupLayout(BlackBorder);
        BlackBorder.setLayout(BlackBorderLayout);
        BlackBorderLayout.setHorizontalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(233, Short.MAX_VALUE)
                .addComponent(HomeAffairsLabel)
                .addGap(206, 206, 206))
        );
        BlackBorderLayout.setVerticalGroup(
            BlackBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BlackBorderLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(HomeAffairsLabel)
                .addContainerGap())
        );

        Background.add(BlackBorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, -1));

        BookSmartIDButton.setText("Book your Smart ID");
        BookSmartIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookSmartIDButtonActionPerformed(evt);
            }
        });
        Background.add(BookSmartIDButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 260, 50));

        EditDetailsButton.setText("Edit your Details");
        EditDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDetailsButtonActionPerformed(evt);
            }
        });
        Background.add(EditDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 290, 50));

        BookPassportButton.setText("Book your Passport Renewal");
        BookPassportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookPassportButtonActionPerformed(evt);
            }
        });
        Background.add(BookPassportButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 260, 50));

        RemoveBookingButton.setText("Remove your Booking");
        RemoveBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveBookingButtonActionPerformed(evt);
            }
        });
        Background.add(RemoveBookingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 290, 50));

        ViewBookingButton.setText("View an Applicant's Booking Date");
        ViewBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBookingButtonActionPerformed(evt);
            }
        });
        Background.add(ViewBookingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 260, 50));

        BookUnabridgedButton.setText("Book your Unabridged Birth Certificate");
        BookUnabridgedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookUnabridgedButtonActionPerformed(evt);
            }
        });
        Background.add(BookUnabridgedButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 290, 50));

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/view/images/Picture 2.png"))); // NOI18N
        Background.add(BackgroundImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 640, 210));

        FileMenu.setText("File");

        LogOutMenu.setText("Log Out");
        LogOutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutMenuActionPerformed(evt);
            }
        });
        FileMenu.add(LogOutMenu);

        HelpMenu.setText("Help");
        HelpMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HelpMenuActionPerformed(evt);
            }
        });
        FileMenu.add(HelpMenu);

        MenuBar.add(FileMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(664, 338));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BookSmartIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookSmartIDButtonActionPerformed
        this.dispose();
        SmartID eng = new SmartID();
        eng.setVisible(true);
        //changes the screen when the book smartID button is clicked
    }//GEN-LAST:event_BookSmartIDButtonActionPerformed

    private void EditDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDetailsButtonActionPerformed
        this.dispose();
        EditDetails eng = new EditDetails();
        eng.setVisible(true);
        //changes the screen when the edit details button is clicked
    }//GEN-LAST:event_EditDetailsButtonActionPerformed

    private void BookPassportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookPassportButtonActionPerformed
        this.dispose();
        Passport eng = new Passport();
        eng.setVisible(true);
        //changes the screen when the book passport button is clicked
    }//GEN-LAST:event_BookPassportButtonActionPerformed

    private void RemoveBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveBookingButtonActionPerformed
        this.dispose();
        RemoveBooking eng = new RemoveBooking();
        eng.setVisible(true);
        //changes the screen when the remove booking button is clicked
    }//GEN-LAST:event_RemoveBookingButtonActionPerformed

    private void ViewBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBookingButtonActionPerformed
        this.dispose();
        ViewBooking eng = new ViewBooking();
        eng.setVisible(true);
        //changes the screen when the view booking button is clicked
    }//GEN-LAST:event_ViewBookingButtonActionPerformed

    private void BookUnabridgedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookUnabridgedButtonActionPerformed
        this.dispose();
        UnabridgedBirthCertificate eng = new UnabridgedBirthCertificate();
        eng.setVisible(true);
        //changes the screen when the book Unabridged birth certificate button 
        //is clicked
    }//GEN-LAST:event_BookUnabridgedButtonActionPerformed

    private void LogOutMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutMenuActionPerformed
        this.dispose();
        WelcomeScreen eng = new WelcomeScreen();
        eng.setVisible(true);
        //changes the screen when the log out button is clicked
    }//GEN-LAST:event_LogOutMenuActionPerformed

    //accesses internet site for help
    private void HelpMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HelpMenuActionPerformed
        try {
            String url = "https://skaterbyron.wixsite.com/homeaffairsonlinehel";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (java.io.IOException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_HelpMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHomeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JPanel BlackBorder;
    private javax.swing.JButton BookPassportButton;
    private javax.swing.JButton BookSmartIDButton;
    private javax.swing.JButton BookUnabridgedButton;
    private javax.swing.JButton EditDetailsButton;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenuItem HelpMenu;
    private javax.swing.JLabel HomeAffairsLabel;
    private javax.swing.JMenuItem LogOutMenu;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JButton RemoveBookingButton;
    private javax.swing.JButton ViewBookingButton;
    // End of variables declaration//GEN-END:variables
}
